language: php

sudo: false
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer require satooshi/php-coveralls:dev-master
  - composer install --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - find .