language: php

sudo: false
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

script: composer test